### PR TITLE
Bump version to 0.0.2?

### PR DESCRIPTION
**Pull request by torsten**
Hi Toby,

What do you think about bumping the version to 0.0.2 and pushing a new release to Clojars?

I'd really like to use the changes from #7 but can't do so yet because the [latest version](https://clojars.org/lein-git-deps) is from 2012.

If I can help with anything just let me know. :)

Thanks,
Torsten

### CODE REVIEW

**Comment by devth** [comment]
:+1:

**Comment by tennety** [comment]
Clojars still shows 0.0.1-SNAPSHOT. Any way 0.0.2 could be made available? Thanks!

**Comment by tobyhede** [comment]
I haven't worked with clojure in ages and have nothing setup! I can add one or both of you to the clojars group to manage the repo?

**Comment by torsten** [comment]
Hi Toby,

I am working more with Clojure recently, if you don't mind I could continue maintaining lein-git-deps.

I created a Clojars account: https://clojars.org/users/torsten

Feel free to add me.

**Comment by tobyhede** [comment]
You should now have access to https://clojars.org/groups/lein-git-deps

**Comment by torsten** [comment]
Ok, thanks!  I published `0.0.2-SNAPSHOT`: https://clojars.org/lein-git-deps

**Comment by tennety** [comment]
:thumbsup: Thanks!

**Pull request closed without merging**
